### ISSUE TITLE
Discuss `test_download_and_delete_fsaverage_surfaces()`

### ISSUE THREAD

**Issue by neukym** [kymata-atlas/kymata-core#293]
Hi @Cai - Can we discuss the test `test_download_and_delete_fsaverage_surfaces()` at some point next week?

It is sensibly testing the downloading of the fsaverage surfaces. I suppose it doesn't matter too much but ... I think this requires it to download 250MB+196MB (i.e almost 0.5GB) by github actions every time we push a commit. I just wanted to make sure that we agreed whether this is sensible.

**Comment by caiw** [comment]
Interesting - this test makes sure that the reliance on downloading from MNE keeps working, but it seems mad to do this each time we push a commit. Maybe we can somehow split this off into a separate CI action which runs like once a month instead? Or just rely on it breaking for us in use rather than test it with CI.

**Comment by caiw** [comment]
Can we exclude certain tests from the on-push CI?

**Comment by neukym** [comment]
yes, we can with:

```
IN_GITHUB_ACTIONS = os.getenv("GITHUB_ACTIONS") == "true"

@pytest.mark.skipif(IN_GITHUB_ACTIONS, reason="Test doesn't work in Github Actions.")
```

**Comment by neukym** [comment]
Fixed.
