### ISSUE TITLE
Doing expression plot is slow for 1000+ functions

### ISSUE THREAD

**Issue by young-x-skyee** [kymata-atlas/kymata-core#354]
When I tried to do expression plot using `expression_plot` for the activation of whisper large model, I noticed that it is very slow with a large memory use (increased slowly) at the beginning and then high CPU use but low memory use. That was where it got stuck.

**Comment by young-x-skyee** [comment]
I think the problem is inside the for loop of plotting all the `show_only ` functions at around line 465 in plot.py. The loop is actually pretty quick when I plot ~1280 functions (~200 iterations/sec on average) but when there are ~80000 functions the loop is much much slower (~3 iterations/sec).

**Comment by caiw** [comment]
Relates to #271

**Comment by caiw** [comment]
I attempted to fix this with #378 but the changes I made had literally zero effect.

Doing a little more profiling, the main slowdown is just simply caused by calling `pyplot.scatter` 1000s of times. If I comment out the call to `scatter`, the main mentioned [here](https://github.com/kymata-atlas/kymata-core/issues/354#issuecomment-2278116331) goes from 40 loops/second up to 200 loops/second for 1000 functions.

The reason it gets progressively slower with additional functions (as mentioned in the linked comment) is I think because each call to `scatter` adds a new distinct `pyplot.Collection` to the axes, and by the time there are 1000s it appears to do some kind of cache invalidation or something which gets progressively more internally laborious with additional collections.

The only way I can think to address this, which could get us *at most* a 5x speedup (which isn't nothing, but isn't nearly as good as the speedup we got in #374), would be to reduce to a single scatter call, with a matrix of colours precomputed and ready to pass to `scatter`'s `c` argument.

Depending on how much this or isn't causing a problem, we could either attempt the above, or close this as a `wontfix` for now and decide that plotting 80k functions on an expression plot is always going to be kind of slow.

@young-x-skyee @neukym I'd appreciate your thoughts!

**Comment by young-x-skyee** [comment]
Yeah I agree with what Cai said. And for my current use, I usually identify the significant transforms by looking at the scatter plot first and then narrow down the number of transforms to be plotted in the expression plot. I'll add the `wontfix` tag now and close this issue at the moment.
